import { createFileRoute, Link } from "@tanstack/react-router";
import { Clock, Mail, MapPin, MessageSquare, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Logo, MallShell } from "@/components/mall/Chrome";
import { ADMIN } from "@/lib/mall-data";

export const Route = createFileRoute("/contact")({ head:()=>({meta:[{title:"Contact Meremoth Mall Support — Douala"},{name:"description",content:"Contact Meremoth Mall support by email or private in-app chat from Douala, Cameroon."},{property:"og:title",content:"Contact Meremoth Mall Support"},{property:"og:description",content:"Private in-app support for buyers and sellers."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component:ContactPage });
function ContactPage(){return <MallShell title="Contact us" back><div className="flex flex-col items-center text-center"><Logo size={64}/><h1 className="mt-3 text-2xl font-bold">Meremoth Mall Support</h1><p className="text-sm text-muted-foreground">Private, in-app help for buyers and sellers</p></div><section className="mt-6 rounded-2xl bg-card p-5 shadow-sm"><div className="grid gap-2"><Button asChild><Link to="/inbox"><MessageSquare className="mr-2 h-4 w-4"/>Open Support Chat</Link></Button><Button asChild variant="outline"><a href={`mailto:${ADMIN.email}`}><Mail className="mr-2 h-4 w-4"/>Send Email</a></Button><Button variant="outline" className="text-destructive" onClick={()=>toast.success("Issue reported. Support will reply in your inbox.")}><TriangleAlert className="mr-2 h-4 w-4"/>Report Issue</Button></div></section><div className="mt-6 space-y-2 rounded-2xl bg-secondary p-4 text-sm"><p className="flex items-center gap-2"><Clock className="h-4 w-4 text-primary"/>Support Hours: {ADMIN.hours}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-primary"/>{ADMIN.location}</p></div></MallShell>}
