import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { BadgeCheck, BriefcaseBusiness, Camera, MapPin, MessageCircle } from "lucide-react";
import { toast } from "sonner";
import { MallShell } from "@/components/mall/Chrome";
import { ListingCard } from "./index";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DOUALA_AREAS, LISTINGS, fcfa } from "@/lib/mall-data";

type Talent={id:string;name:string;skill:string;area:string;rate:number;experience:number;available:boolean;verified:boolean;initials:string};
const TALENT:Talent[]=[
 {id:"talent-1",name:"Martine N.",skill:"Electrician",area:"Akwa",rate:12000,experience:6,available:true,verified:true,initials:"MN"},
 {id:"talent-2",name:"Boris E.",skill:"Driver",area:"Deido",rate:10000,experience:8,available:true,verified:true,initials:"BE"},
 {id:"talent-3",name:"Carine M.",skill:"Computer Repair",area:"Bonaberi",rate:15000,experience:4,available:false,verified:false,initials:"CM"},
];
export const Route=createFileRoute("/jobs")({head:()=>({meta:[{title:"Jobs & Find Talent in Douala — Meremoth Mall"},{name:"description",content:"Browse job offers or find verified electricians, plumbers, drivers and repair professionals across Douala."},{property:"og:title",content:"Jobs & Find Talent — Meremoth Mall"},{property:"og:description",content:"Post work, find work, or chat with local talent in Douala."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:JobsPage});
function JobsPage(){return <MallShell title="Jobs" back><h1 className="text-2xl font-bold">Jobs in Douala</h1><Tabs defaultValue="offers" className="mt-4"><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="offers">Job Offers</TabsTrigger><TabsTrigger value="talent">Find Talent</TabsTrigger></TabsList><TabsContent value="offers"><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{LISTINGS.filter(l=>l.category==="jobs").map(l=><ListingCard key={l.id} listing={l}/>)}</div></TabsContent><TabsContent value="talent"><div className="mt-4 flex items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Skilled people ready for work near you.</p><PostSkillDialog/></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{TALENT.map(t=><TalentCard key={t.id} talent={t}/>)}</div></TabsContent></Tabs></MallShell>}
function TalentCard({talent}:{talent:Talent}){return <article className="rounded-lg border border-border bg-card p-4 shadow-sm"><div className="flex gap-3"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-secondary font-bold text-primary">{talent.initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1"><h2 className="font-bold">{talent.name}</h2>{talent.available&&<span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-bold text-primary-foreground">Available Now</span>}</div><p className="text-sm font-semibold">{talent.skill}</p><p className="text-xs text-muted-foreground"><MapPin className="mr-1 inline h-3 w-3"/>{talent.area} · {talent.experience} years</p></div></div><p className="mt-3 text-base font-bold">{fcfa(talent.rate)} / day</p>{talent.verified&&<p className="mt-1 flex items-center gap-1 text-xs font-semibold text-primary"><BadgeCheck className="h-4 w-4"/>Verified by Meremoth</p>}<Button asChild variant="outline" className="mt-3 w-full"><Link to="/chat/$sellerId" params={{sellerId:talent.id}}><MessageCircle className="mr-2 h-4 w-4"/>Contact Talent</Link></Button></article>}
function PostSkillDialog(){const [open,setOpen]=useState(false);return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm"><BriefcaseBusiness className="mr-1 h-4 w-4"/>Post Your Skill - Find Work</Button></DialogTrigger><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Post Your Skill - Find Work</DialogTitle></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();setOpen(false);toast.success("Your skill profile is posted for review.")}}><Field id="talent-name" label="Full name"/><Field id="talent-skill" label="Skill" placeholder="Electrician, Plumber, Driver..."/><div className="space-y-1.5"><Label htmlFor="talent-area">Area</Label><select id="talent-area" className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{DOUALA_AREAS.map(a=><option key={a}>{a}</option>)}</select></div><Field id="talent-rate" label="Daily Rate (FCFA)" type="number"/><Field id="talent-years" label="Years Experience" type="number"/><div className="space-y-1.5"><Label htmlFor="talent-photo">Photo</Label><Input id="talent-photo" type="file" accept="image/*"/></div><div className="space-y-1.5"><Label htmlFor="talent-cni">CNI for verification (optional)</Label><Input id="talent-cni" type="file" accept="image/*,.pdf"/><p className="flex items-center gap-1 text-xs text-muted-foreground"><Camera className="h-3 w-3"/>Uploading CNI qualifies your profile for verification review.</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked/>Available Now</label><Button type="submit" className="w-full">Post Your Skill - Find Work</Button></form></DialogContent></Dialog>}
function Field({id,label,type="text",placeholder}:{id:string;label:string;type?:string;placeholder?:string}){return <div className="space-y-1.5"><Label htmlFor={id}>{label}</Label><Input id={id} type={type} placeholder={placeholder} required/></div>}
