/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddListingRouteImport } from './routes/add-listing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgencyLoginRouteImport } from './routes/agency-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeSellerRouteImport } from './routes/become-seller'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FindForMeRouteImport } from './routes/find-for-me'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MeremothMallHomepageUiRouteImport } from './routes/meremoth-mall-homepage-ui'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WantedRouteImport } from './routes/wanted'
import { Route as ChatSellerIdRouteImport } from './routes/chat.$sellerId'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ApiPublicLogisticsAutoReleaseRouteImport } from './routes/api/public/logistics/auto-release'
import { Route as ApiPublicWalletCinetpayNotifyRouteImport } from './routes/api/public/wallet/cinetpay-notify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddListingRoute = AddListingRouteImport.update({
  id: '/add-listing',
  path: '/add-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyLoginRoute = AgencyLoginRouteImport.update({
  id: '/agency-login',
  path: '/agency-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeSellerRoute = BecomeSellerRouteImport.update({
  id: '/become-seller',
  path: '/become-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FindForMeRoute = FindForMeRouteImport.update({
  id: '/find-for-me',
  path: '/find-for-me',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MeremothMallHomepageUiRoute = MeremothMallHomepageUiRouteImport.update({
  id: '/meremoth-mall-homepage-ui',
  path: '/meremoth-mall-homepage-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WantedRoute = WantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSellerIdRoute = ChatSellerIdRouteImport.update({
  id: '/chat/$sellerId',
  path: '/chat/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogisticsAutoReleaseRoute =
  ApiPublicLogisticsAutoReleaseRouteImport.update({
    id: '/api/public/logistics/auto-release',
    path: '/api/public/logistics/auto-release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWalletCinetpayNotifyRoute =
  ApiPublicWalletCinetpayNotifyRouteImport.update({
    id: '/api/public/wallet/cinetpay-notify',
    path: '/api/public/wallet/cinetpay-notify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-listing': typeof AddListingRoute
  '/admin': typeof AdminRoute
  '/agency-login': typeof AgencyLoginRoute
  '/auth': typeof AuthRoute
  '/become-seller': typeof BecomeSellerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/find-for-me': typeof FindForMeRoute
  '/inbox': typeof InboxRoute
  '/jobs': typeof JobsRoute
  '/meremoth-mall-homepage-ui': typeof MeremothMallHomepageUiRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/wanted': typeof WantedRoute
  '/chat/$sellerId': typeof ChatSellerIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/public/logistics/auto-release': typeof ApiPublicLogisticsAutoReleaseRoute
  '/api/public/wallet/cinetpay-notify': typeof ApiPublicWalletCinetpayNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-listing': typeof AddListingRoute
  '/admin': typeof AdminRoute
  '/agency-login': typeof AgencyLoginRoute
  '/auth': typeof AuthRoute
  '/become-seller': typeof BecomeSellerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/find-for-me': typeof FindForMeRoute
  '/inbox': typeof InboxRoute
  '/jobs': typeof JobsRoute
  '/meremoth-mall-homepage-ui': typeof MeremothMallHomepageUiRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/wanted': typeof WantedRoute
  '/chat/$sellerId': typeof ChatSellerIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/public/logistics/auto-release': typeof ApiPublicLogisticsAutoReleaseRoute
  '/api/public/wallet/cinetpay-notify': typeof ApiPublicWalletCinetpayNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-listing': typeof AddListingRoute
  '/admin': typeof AdminRoute
  '/agency-login': typeof AgencyLoginRoute
  '/auth': typeof AuthRoute
  '/become-seller': typeof BecomeSellerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/find-for-me': typeof FindForMeRoute
  '/inbox': typeof InboxRoute
  '/jobs': typeof JobsRoute
  '/meremoth-mall-homepage-ui': typeof MeremothMallHomepageUiRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/wanted': typeof WantedRoute
  '/chat/$sellerId': typeof ChatSellerIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/public/logistics/auto-release': typeof ApiPublicLogisticsAutoReleaseRoute
  '/api/public/wallet/cinetpay-notify': typeof ApiPublicWalletCinetpayNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-listing'
    | '/admin'
    | '/agency-login'
    | '/auth'
    | '/become-seller'
    | '/contact'
    | '/dashboard'
    | '/find-for-me'
    | '/inbox'
    | '/jobs'
    | '/meremoth-mall-homepage-ui'
    | '/pricing'
    | '/search'
    | '/terms'
    | '/wallet'
    | '/wanted'
    | '/chat/$sellerId'
    | '/listing/$id'
    | '/api/public/logistics/auto-release'
    | '/api/public/wallet/cinetpay-notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-listing'
    | '/admin'
    | '/agency-login'
    | '/auth'
    | '/become-seller'
    | '/contact'
    | '/dashboard'
    | '/find-for-me'
    | '/inbox'
    | '/jobs'
    | '/meremoth-mall-homepage-ui'
    | '/pricing'
    | '/search'
    | '/terms'
    | '/wallet'
    | '/wanted'
    | '/chat/$sellerId'
    | '/listing/$id'
    | '/api/public/logistics/auto-release'
    | '/api/public/wallet/cinetpay-notify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-listing'
    | '/admin'
    | '/agency-login'
    | '/auth'
    | '/become-seller'
    | '/contact'
    | '/dashboard'
    | '/find-for-me'
    | '/inbox'
    | '/jobs'
    | '/meremoth-mall-homepage-ui'
    | '/pricing'
    | '/search'
    | '/terms'
    | '/wallet'
    | '/wanted'
    | '/chat/$sellerId'
    | '/listing/$id'
    | '/api/public/logistics/auto-release'
    | '/api/public/wallet/cinetpay-notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddListingRoute: typeof AddListingRoute
  AdminRoute: typeof AdminRoute
  AgencyLoginRoute: typeof AgencyLoginRoute
  AuthRoute: typeof AuthRoute
  BecomeSellerRoute: typeof BecomeSellerRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FindForMeRoute: typeof FindForMeRoute
  InboxRoute: typeof InboxRoute
  JobsRoute: typeof JobsRoute
  MeremothMallHomepageUiRoute: typeof MeremothMallHomepageUiRoute
  PricingRoute: typeof PricingRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  WantedRoute: typeof WantedRoute
  ChatSellerIdRoute: typeof ChatSellerIdRoute
  ListingIdRoute: typeof ListingIdRoute
  ApiPublicLogisticsAutoReleaseRoute: typeof ApiPublicLogisticsAutoReleaseRoute
  ApiPublicWalletCinetpayNotifyRoute: typeof ApiPublicWalletCinetpayNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-listing': {
      id: '/add-listing'
      path: '/add-listing'
      fullPath: '/add-listing'
      preLoaderRoute: typeof AddListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-login': {
      id: '/agency-login'
      path: '/agency-login'
      fullPath: '/agency-login'
      preLoaderRoute: typeof AgencyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-seller': {
      id: '/become-seller'
      path: '/become-seller'
      fullPath: '/become-seller'
      preLoaderRoute: typeof BecomeSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-for-me': {
      id: '/find-for-me'
      path: '/find-for-me'
      fullPath: '/find-for-me'
      preLoaderRoute: typeof FindForMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meremoth-mall-homepage-ui': {
      id: '/meremoth-mall-homepage-ui'
      path: '/meremoth-mall-homepage-ui'
      fullPath: '/meremoth-mall-homepage-ui'
      preLoaderRoute: typeof MeremothMallHomepageUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanted': {
      id: '/wanted'
      path: '/wanted'
      fullPath: '/wanted'
      preLoaderRoute: typeof WantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sellerId': {
      id: '/chat/$sellerId'
      path: '/chat/$sellerId'
      fullPath: '/chat/$sellerId'
      preLoaderRoute: typeof ChatSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logistics/auto-release': {
      id: '/api/public/logistics/auto-release'
      path: '/api/public/logistics/auto-release'
      fullPath: '/api/public/logistics/auto-release'
      preLoaderRoute: typeof ApiPublicLogisticsAutoReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wallet/cinetpay-notify': {
      id: '/api/public/wallet/cinetpay-notify'
      path: '/api/public/wallet/cinetpay-notify'
      fullPath: '/api/public/wallet/cinetpay-notify'
      preLoaderRoute: typeof ApiPublicWalletCinetpayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddListingRoute: AddListingRoute,
  AdminRoute: AdminRoute,
  AgencyLoginRoute: AgencyLoginRoute,
  AuthRoute: AuthRoute,
  BecomeSellerRoute: BecomeSellerRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FindForMeRoute: FindForMeRoute,
  InboxRoute: InboxRoute,
  JobsRoute: JobsRoute,
  MeremothMallHomepageUiRoute: MeremothMallHomepageUiRoute,
  PricingRoute: PricingRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  WantedRoute: WantedRoute,
  ChatSellerIdRoute: ChatSellerIdRoute,
  ListingIdRoute: ListingIdRoute,
  ApiPublicLogisticsAutoReleaseRoute: ApiPublicLogisticsAutoReleaseRoute,
  ApiPublicWalletCinetpayNotifyRoute: ApiPublicWalletCinetpayNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
